spring:
  application:
    name: item-service
    
#server:
#  port: 8001

---
spring:
  profiles: item1
  
server:
  port: 8001
  
eureka:
  client:
    service-url:
                 #结合云服务才能设置其他选项
      defaultZone: http://176.5.16.211:2001/eureka,http://176.5.16.211:2002/eureka
---
spring:
  profiles: item2

server:
  port: 8002


eureka:
  client:
    service-url:
                 #结合云服务才能设置其他选项
      defaultZone: http://176.5.16.211:2001/eureka,http://176.5.16.211:2002/eureka
